# Generated by Django 3.1.5 on 2021-01-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restorant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaresto', models.CharField(max_length=50, null=True)),
                ('notlp', models.CharField(max_length=12, null=True)),
                ('alamat', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
