# Generated by Django 3.1.5 on 2021-01-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210110_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='status',
            field=models.CharField(choices=[('Tersedia', 'Tersedia'), ('Tidak Tersedia', 'Tidak Tersedia')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='harga',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='restorant',
            name='status',
            field=models.CharField(choices=[('Buka', 'Buka'), ('Tutup', 'Tutup')], max_length=50, null=True),
        ),
    ]
