# Generated by Django 3.1.5 on 2021-01-13 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210110_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='penyedia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.restorant'),
            preserve_default=False,
        ),
    ]
