# Generated by Django 3.1.5 on 2021-01-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_restorant_milik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='status',
            field=models.CharField(choices=[('Tersedia', 'Tersedia'), ('Habis', 'Habis')], max_length=50, null=True),
        ),
    ]
