# Generated by Django 3.1.5 on 2021-01-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_restorant_foto_resto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restorant',
            name='foto_resto',
            field=models.ImageField(default='/default.jpg', upload_to='documents/'),
        ),
    ]
