# Generated by Django 3.1.5 on 2021-01-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210113_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='restorant',
            name='deskripsi',
            field=models.TextField(default='ini deskripsi'),
            preserve_default=False,
        ),
    ]
