# Generated by Django 3.1.5 on 2021-01-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210119_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='restorant',
            name='foto_menu',
            field=models.ImageField(default='/default.jpg', upload_to='documents/'),
        ),
    ]
