# Generated by Django 3.0.2 on 2021-01-24 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_restorant_foto_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restorant',
            name='milik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restorant', to=settings.AUTH_USER_MODEL),
        ),
    ]
