# Generated by Django 3.0.2 on 2021-01-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210125_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restorant',
            name='deskripsi',
            field=models.TextField(null=True),
        ),
    ]
